### ISSUE TITLE
Suport for S3

### ISSUE THREAD

**Issue by felipegenef** [clems4ever/anytype-backup-node#1]
Hey, I´ve been trying to understand and implement a self-hosted node for myself. Any chance this yml can be used for S3 instead of minio?
Also, it would be nice to know how to build my own client for the self-hosted server I will create with your Dockerfile. You don´t have to make a doc for it, just link the official one of Anytype on the Readme.md. 
It would help me a lot! 
I´ll try to contribute as much as I can if you let me.

**Comment by clems4ever** [comment]
Hello @felipegenef , I think the backup node deployed by anytype is using a standard S3 from what I can deduce from the code they wrote. I had to make a fix in their library to use minio and make this project work.

Regarding building the clients, as stated in the readme, is is not something I will invest time on because the anytype team is currently working on a way around and because it's not easy. I have done it for the web client but I have not managed to make it with the Android client. My opinion is that the process is complex whatever the client so you'd better wait the way around unless you have few hours to spend on it.

Hope it helps.

**Comment by felipegenef** [comment]
I've done it with Syncthing and it has been working so far. Unfortunately, it stores my data on an EBS, which is much more expensive than S3. Anyway, I've made some tests and if my PC explodes it will be able to sync back into another PC  😆 . It is not perfect but works fine until there is no easier solution.

**Comment by clems4ever** [comment]
Glad to here that you have found a solution. I will close the issue since there is no actionable item but if you have further details about what is not working for you with this project, please reopen the issue with the details.
Thanks.
